language: node_js

node_js:
  - "10"
  - "12"
  - "node"

env:
  - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9

script:
  - npm run check

after_success:
  - npm run coveralls
